Implement formatting check for long hyphen
GrafeasGroup/tor pull request #261
Opened 2021-08-06 08:27 UTC by fulminatingmoat

Not too necessary since missing separator check will detect it as well

2021-08-08 11:07 UTC, TimJentzsch requested changes
The implementation itself looks good, however we also need to define the response string for this formatting issue in `tor/strings/en_US.yml`. For examples you can take a look at the other formatting issues.

2021-08-08 11:07 UTC, TimJentzsch commented on test/validation/test_formatting_validation.py
> +        ("Word\n    int x = 1\nWord", False),
I would add `("---", False)` here as well, as this is the most commonly used separator string.

2021-11-25 09:00 UTC, TimJentzsch approved these changes

2021-11-25 09:01 UTC, TimJentzsch requested changes
We still need to define the corresponding strings for the bot response.

2022-01-12 08:02 UTC, TimJentzsch commented
Here we still need to define the bot response for the volunteers, you can take https://github.com/GrafeasGroup/tor/blob/main/tor/strings/en_US.yml#L209-L319 as examples :)

2022-02-03 22:26 UTC, TheLonelyGhost requested changes

2022-02-03 22:26 UTC, TheLonelyGhost commented on tor/validation/formatting_validation.py
> +        if AUTOGENERATED_LONG_HYPHEN_PATTERN.search(transcription) is not None
Why not drop the regex and do a simple `x in y` check?

```suggestion
        if "\u2014" in transcription  # \u2014 == em dash == "long hyphen"

```

2022-02-03 22:26 UTC, TheLonelyGhost commented on test/validation/test_formatting_validation.py
> +    """Test if autogenerated long hyphens are detected."""
The long hyphen isn't always auto-generated, so perhaps "accidental" would be a better descriptor than "autogenerated"?

Side note: if settings for "smart quotes" (and the like) are enabled on macOS, it automatically replaces `--` with `—` there too. Not just mobile. 😄

2022-03-17 06:25 UTC, closed without merging

2022-03-17 06:27 UTC, TheLonelyGhost commented
No comments and no meaningful code updates in months. Closing this since it seems pretty stale to me. Feel free to reopen if the mood strikes to pick this up again!