Fix false positive on multi-heading (i.e. ## Heading)
GrafeasGroup/tor pull request #270
Opened 2021-08-12 20:57 UTC by TheodoreHua

Closes #269

2021-08-12 21:59 UTC, itsthejoker requested changes
The regex suggestion does fix the issue but opens up a different can of worms with allowing multiple octothorpes in the beginning of a line. See here for an example: https://regex101.com/r/d2gPNh/1

2021-08-12 23:04 UTC, TheodoreHua commented
First time I've heard it get called octothorpe, anyway, this should fix both issues https://regex101.com/r/BShoSy/1

2021-08-13 16:23 UTC, itsthejoker commented
Yessss thank you!

2021-08-13 16:23 UTC, itsthejoker approved these changes

2021-08-13 16:24 UTC, merged